name: Publish to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          path: vaultofknowledge
          fetch-depth: 1
    
      - name: Install dependencies and run build
        run: |
          cd ${{ github.workspace }}
          pip install --upgrade pip
          pip install git+https://github.com/blacklightpy/obsidian-html
          sudo apt install git-restore-mtime
          cd vaultofknowledge
          git restore-mtime
          cd ..
          obsidianhtml convert -i vaultofknowledge/config.yaml -v
          touch html/.nojekyll
    
      - name: Publish to Github Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: html # The directory where your assets are generated
          SQUASH_HISTORY: true # Squashes branch history to avoid file buildup
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
